### ISSUE TITLE
Is it possible to add goes2go to the geemap package?

### ISSUE THREAD

**Issue by ErikSeras** [blaylockbk/goes2go#1]
Hi,

Thank you very much, thanks to this repository it helped me to fix [a deficiency of Google Earth Engine](https://github.com/giswqs/geemap/discussions/290
) (GEE): the data is available with [1](https://developers.google.com/earth-engine/datasets/catalog/NOAA_GOES_16_MCMIPF) or [2](https://developers.google.com/earth-engine/datasets/catalog/COPERNICUS_S5P_NRTI_L3_NO2) days of delay. I would like the `goes2go` functionalities to be in the [`geemap`](https://github.com/giswqs/geemap) package so that everyone can have recent (via AWS) and past (via GEE) data from GOES or another AWS dataset (Sentinel, Landsat, etc.).

**Comment by blaylockbk** [comment]
Happy to hear this package helped you. GOES data is also available on [Google Cloud Platform](https://console.cloud.google.com/marketplace/product/noaa-public/goes-16?pli=1&project=python-232920&folder=&organizationId=) . If you are working with the Google Earth Engine, it might make sense to get the data from GCP instead of AWS.

**Comment by blaylockbk** [comment]
closing issue as I am not working on this
