### ISSUE TITLE
Issue on specific day for reading data

### ISSUE THREAD

**Issue by thomasdewitt** [blaylockbk/goes2go#22]
Hello, 

I am downloading data for many days, which works fine most of the time, but there is a specific day that causes an issue. Here is my code (in a loop over multiple scene.target_time):
```
        print(scene.satellite_name[-4:])
        print(scene.target_time)
        data = goes_nearesttime(scene.target_time, satellite=scene.satellite_name[-4:], product='ABI-L2-ACMF', save_dir=data_dir+'GOES/', verbose=False)
```
and it produces:
```

WEST
2021-07-19 21:00:00
WEST
2021-07-20 21:00:00
WEST
2021-07-21 21:00:00
WEST
2021-07-22 21:00:00
Traceback (most recent call last):
...
  File "/uufs/chpc.utah.edu/common/home/u1020524/cloud-distributions-chpc/data_reader.py", line 1012, in _GOES_read
    data = goes_nearesttime(scene.target_time, satellite=scene.satellite_name[-4:], product='ABI-L2-ACMF', save_dir=data_dir+'GOES/', verbose=False)
  File "/uufs/chpc.utah.edu/common/home/u1020524/software/pkg/miniconda3/lib/python3.9/site-packages/goes2go/data.py", line 640, in goes_nearesttime
    df = _goes_file_df(satellite, product, start, end, refresh=s3_refresh)
  File "/uufs/chpc.utah.edu/common/home/u1020524/software/pkg/miniconda3/lib/python3.9/site-packages/goes2go/data.py", line 151, in _goes_file_df
    df["file"].str.rsplit("_", expand=True, n=3).loc[:, 1:]
  File "/uufs/chpc.utah.edu/common/home/u1020524/software/pkg/miniconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
...
TypeError: cannot do slice indexing on Index with these indexers [1] of type int
```
(I have omitted some of the traceback) As you can see, it works fine for most days but there seems to be a problem at the specific time of 2021-07-22 21:00:00. I am not sure what is wrong on that day.

Thanks

**Comment by blaylockbk** [comment]
Hi @thomasdewitt. Thanks for finding and reporting this bug. _I think_ this error was fixed in an unrelated update that I just pushed to the main branch.

Can you try it again with those changes? This worked for me:

```python
from goes2go.data import goes_nearesttime
data = goes_nearesttime(
    attime='2021-07-19 21:00:00',
    satellite=17,
    product='ABI-L2-ACMF',
)
data
```
<img width="487" alt="image" src="https://user-images.githubusercontent.com/6249613/172035076-c6d73bc9-05ad-4cc2-bb45-2273e19b7fcb.png">


There is also a new, more convenient way of downloading the data by creating a new GOES object

```python
from goes2go import GOES
G = GOES(satellite=17, product='ABI-L2-ACM', domain='F')

# Download all files within a timerange (don't open with xarray)
G.timerange('2021-07-19 21:00', '2021-07-20 00:00')
```
<img width="474" alt="image" src="https://user-images.githubusercontent.com/6249613/172035162-0dcedc0f-6239-4fd7-8a47-7141eb4b2b54.png">

```python
# Read a file with xarray
G.nearesttime('2021-07-19 21:00:00')
```
<img width="482" alt="image" src="https://user-images.githubusercontent.com/6249613/172035173-02372bb5-6a00-4fbe-9bb7-d106d11c0e58.png">

**Comment by blaylockbk** [comment]
Closing this for now, but if you still run into issues, feel free to reopen or create a new issue 😎

**Comment by thomasdewitt** [comment]
Hey, thanks for the fix and prompt reply. Unfortunately I was not able to test it as my research took a new direction, but it does look fixed from your reply. Hopefully I will in the future though! Thanks
