### ISSUE TITLE
GOES-EAST product match

### ISSUE THREAD

**Issue by EmanuelCastanho** [blaylockbk/goes2go#70]
Hi,

I am starting to work with GOES data and while looking for an API to download the data I found your package :)

I have doubts after checking your list of products, what would be the codes of the following two products underlined in red? Are they available? I need to access the most recent data from one of these products and convert to GeoTIFF.

Thank you

![Screenshot 2023-08-01 at 16 15 27](https://github.com/blaylockbk/goes2go/assets/69935277/e66f6738-393b-45c8-b879-8df4f198dbc9)

**Comment by cmo84** [comment]
Hi Emanuel, I was one of the algorithm developers for the GOES ground system.   These products are created downstream of the actual level 2 processing, so there wouldn't be product codes for download from the bucket.  You should check out the RGB recipes section of the docs in order to be able to produce these images from the ABI L2 CMIP data https://blaylockbk.github.io/goes2go/_build/html/reference_guide/index.html#rgb-recipes

**Comment by EmanuelCastanho** [comment]
Amazing, thank you!
