### ISSUE TITLE
SeaSpray RGB not available in 2023.4.2

### ISSUE THREAD

**Issue by bryanguarente** [blaylockbk/goes2go#73]
Brian,
I think you may have inadvertently removed the SeaSpray RGB from rgb.py.  This makes an error message when trying to make the SeaSpray RGB.  

 if product =='SeaSpray':
--> 103     RGB = getattr(GABI.rgb,'SeaSpray')()
    104     im = ax.imshow(RGB, transform=GABI.rgb.crs, 
    105                    extent=[xdat.min(), xdat.max(), ydat.min(), ydat.max()])
    107 ax.add_feature(cf.BORDERS, edgecolor=edgecolor)

AttributeError: 'rgbAccessor' object has no attribute 'SeaSpray'

I don't currently have time to figure out exactly what the problem is and send a pull request, but thought you might be able to test it on your end before I get to it.  Just letting you know.  It would be worth checking on the other added RGBs (Air Mass Tropical) too.

Thanks,
Bryan

**Comment by bryanguarente** [comment]
If I am reading this correctly, it looks like you just haven't pushed those edits out yet to the whl files or conda, so I am guessing I am jumping the gun on this.  Sorry.  I will close this one myself.

**Comment by blaylockbk** [comment]
Hi @bryanguarente 
I got around to making the releases more automated and easier 😃. 
GOES-2-go 2023.8.0 is now on PyPI https://pypi.org/project/goes2go/ (and conda-forge is pending).

I didn't test the installation extensively, so if you see anything let me know.
- Pinned cartopy 0.22.0, because it's so nice not having the GEOS dependency.
- Pinned s3fs>=2023.6.0 because another use had issues with an older version
